# Generated by Django 5.1.5 on 2026-03-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(help_text='URL or base64 data for the card image')),
                ('label', models.CharField(blank=True, help_text='Text shown on the card (e.g. brand name)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='The New Standard for Influencer Marketing', max_length=100)),
                ('title', models.CharField(default='Where Creators & Brands Innovate', max_length=200)),
                ('subtitle', models.TextField(default='Discover, collaborate, and scale your reach. The all-in-one platform connecting authentic creators with world-class brands.')),
                ('creator_button_text', models.CharField(default='Sign up as a Creator', max_length=50)),
                ('brand_button_text', models.CharField(default='Sign up as a Brand', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hero Content',
            },
        ),
    ]
