# Generated by Django 5.1.5 on 2026-03-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocard',
            name='attachment_bg_color',
            field=models.CharField(default='#FFFFFF', help_text='Background color of the attachment', max_length=50),
        ),
        migrations.AddField(
            model_name='herocard',
            name='attachment_label',
            field=models.CharField(blank=True, help_text='Text for the overlapping small badge', max_length=50),
        ),
        migrations.AddField(
            model_name='herocard',
            name='attachment_text_color',
            field=models.CharField(default='#000000', help_text='Text color of the attachment', max_length=50),
        ),
        migrations.AddField(
            model_name='herocard',
            name='background_color',
            field=models.CharField(default='#F3F4F6', help_text='Hex color or Tailwind bg- class', max_length=50),
        ),
        migrations.AddField(
            model_name='herocard',
            name='card_size',
            field=models.CharField(choices=[('small', 'Small (Badge)'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='herocard',
            name='text_color',
            field=models.CharField(default='#000000', help_text='Hex color or Tailwind text- class', max_length=50),
        ),
        migrations.AlterField(
            model_name='herocard',
            name='image_url',
            field=models.TextField(blank=True, help_text='URL for the card image. Leave blank for text-only badges.', null=True),
        ),
        migrations.AlterField(
            model_name='herocard',
            name='label',
            field=models.CharField(blank=True, help_text='Main text shown on the card', max_length=50),
        ),
    ]
