# Generated by Django 5.1.5 on 2026-03-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_herocard_attachment_bg_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herocard',
            name='attachment_bg_color',
        ),
        migrations.RemoveField(
            model_name='herocard',
            name='attachment_label',
        ),
        migrations.RemoveField(
            model_name='herocard',
            name='attachment_text_color',
        ),
        migrations.RemoveField(
            model_name='herocard',
            name='is_active',
        ),
    ]
