# Generated by Django 4.2.16 on 2026-03-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_remove_herocard_attachment_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocard',
            name='attachment_bg_color',
            field=models.CharField(default='#FFFFFF', help_text='Background color of the attachment', max_length=50),
        ),
        migrations.AddField(
            model_name='herocard',
            name='attachment_label',
            field=models.CharField(blank=True, help_text='Text for the overlapping small badge', max_length=50),
        ),
        migrations.AddField(
            model_name='herocard',
            name='attachment_text_color',
            field=models.CharField(default='#000000', help_text='Text color of the attachment', max_length=50),
        ),
        migrations.AddField(
            model_name='herocard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
