# Generated by Django 4.2.16 on 2026-03-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_herocard_attachment_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocontent',
            name='anim_image1',
            field=models.TextField(blank=True, default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=200&fit=crop', null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='anim_image2',
            field=models.TextField(blank=True, default='https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&h=200&fit=crop', null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='anim_image3',
            field=models.TextField(blank=True, default='https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop', null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='anim_image4',
            field=models.TextField(blank=True, default='https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&h=200&fit=crop', null=True),
        ),
        migrations.AddField(
            model_name='herocontent',
            name='anim_text',
            field=models.TextField(default="Maximize Your {img1} Brand's\nGrowth and {img2}{img3}{img4} Skyrocket Sales\nby Leveraging the Potential\nof Creator Marketing"),
        ),
    ]
