# Generated by Django 4.2.16 on 2026-03-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_herocontent_anim_image1_herocontent_anim_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(help_text='URL for the catalog image')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
