# Generated by Django 5.1.5 on 2026-03-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_catalogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimage',
            name='accent_text',
            field=models.CharField(default='MODERN MINIMALISM', max_length=100),
        ),
        migrations.AddField(
            model_name='catalogimage',
            name='subtitle',
            field=models.CharField(default='URBAN', max_length=100),
        ),
        migrations.AddField(
            model_name='catalogimage',
            name='tagline',
            field=models.CharField(default='Discover AW24 Collection', max_length=100),
        ),
        migrations.AddField(
            model_name='catalogimage',
            name='title',
            field=models.CharField(default='THE NEW EDIT', max_length=100),
        ),
    ]
