# Generated by Django 6.0.2 on 2026-02-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0002_collaborationrequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='payment_added_to_pending',
            field=models.BooleanField(default=False, help_text='Track if payment was added to pending balance'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
