# Generated by Django 4.2.16 on 2026-02-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='facebook_page',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='linkedin_profile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='preferred_platforms',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred social media platforms'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='snapchat_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='twitch_channel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('fashion', 'Fashion'), ('beauty', 'Beauty'), ('fitness', 'Fitness'), ('food', 'Food'), ('travel', 'Travel'), ('tech', 'Technology'), ('lifestyle', 'Lifestyle'), ('gaming', 'Gaming')], max_length=20),
        ),
    ]
