# Generated by Django 4.2.16 on 2026-02-04 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_influencerprofile_facebook_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerprofile',
            name='tiktok_handle',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='twitter_handle',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='facebook_page',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='linkedin_profile',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='twitch_channel',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='snapchat_handle',
        ),
    ]
