# Generated by Django 4.2.16 on 2026-02-05 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20260204_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
