# Generated by Django 6.0.2 on 2026-02-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_influencerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='Languages spoken'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='location',
            field=models.CharField(blank=True, help_text='City, Country', max_length=100),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='portfolio_videos',
            field=models.JSONField(blank=True, default=list, help_text='List of portfolio video URLs'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='rate_per_reel',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rate for a reel/short video', max_digits=10),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='rate_per_story',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rate for a story', max_digits=10),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='rate_per_video',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rate for a full video', max_digits=10),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='tiktok_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='website_url',
            field=models.URLField(blank=True, help_text='Personal website or portfolio'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='portfolio_images',
            field=models.JSONField(blank=True, default=list, help_text='List of portfolio image URLs'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='profile_image',
            field=models.URLField(blank=True, help_text='Profile picture URL'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='rate_per_post',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rate for a single post', max_digits=10),
        ),
    ]
