# Generated by Django 6.0.2 on 2026-02-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_influencerprofile_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerprofile',
            name='tiktok_handle',
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='twitter_handle',
        ),
    ]
