# Generated by Django 6.0.2 on 2026-02-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_influencerprofile_tiktok_handle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerprofile',
            name='portfolio_images',
            field=models.JSONField(blank=True, default=list, help_text='List of portfolio image URLs or base64 data'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='portfolio_videos',
            field=models.JSONField(blank=True, default=list, help_text='List of portfolio video URLs or base64 data'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='profile_image',
            field=models.TextField(blank=True, help_text='Profile picture URL or base64 data'),
        ),
    ]
