# Generated by Django 4.2.16 on 2026-02-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_influencerprofile_portfolio_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='latest_product_review_link',
            field=models.URLField(blank=True, help_text='Link to latest product review'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='most_viewed_content_link',
            field=models.URLField(blank=True, help_text='Link to most viewed content'),
        ),
    ]
