# Generated by Django 6.0.2 on 2026-02-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_influencerprofile_latest_product_review_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='latest_product_review_cover',
            field=models.TextField(blank=True, help_text='Cover image URL or base64 data for latest product review'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='most_viewed_content_cover',
            field=models.TextField(blank=True, help_text='Cover image URL or base64 data for most viewed content'),
        ),
    ]
