# Generated by Django 6.0.2 on 2026-02-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_influencerprofile_latest_product_review_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='latest_product_review_likes',
            field=models.PositiveIntegerField(default=0, help_text='Like count for latest product review'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='latest_product_review_views',
            field=models.PositiveIntegerField(default=0, help_text='View count for latest product review'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='most_viewed_content_likes',
            field=models.PositiveIntegerField(default=0, help_text='Like count for most viewed content'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='most_viewed_content_views',
            field=models.PositiveIntegerField(default=0, help_text='View count for most viewed content'),
        ),
    ]
