# Generated by Django 6.0.2 on 2026-02-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_companyprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='pending_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total pending payments for completed campaigns', max_digits=12),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='total_spend',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount spent on paid campaigns', max_digits=12),
        ),
    ]
