# Generated by Django 5.0 on 2026-02-11 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_approval_status_user_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Set to Pending')], help_text='Type of action performed', max_length=20)),
                ('previous_status', models.CharField(blank=True, help_text='Status before the change', max_length=20)),
                ('new_status', models.CharField(help_text='Status after the change', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for rejection or notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of admin', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('admin', models.ForeignKey(help_text='Admin who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The influencer whose status was changed', on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval Audit Log',
                'verbose_name_plural': 'Approval Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
