# Generated by Django 5.1.5 on 2026-02-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_approvalauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_shown',
            field=models.BooleanField(default=False, help_text='Whether approval popup has been shown to user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Detailed approval status', max_length=20),
        ),
    ]
