# Generated by Django 5.1.5 on 2026-02-11 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('payment', 'Payment'), ('campaign', 'Campaign'), ('account', 'Account'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('admin_reply', models.TextField(blank=True, null=True)),
                ('admin_replied_at', models.DateTimeField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='support_screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_ticket_replies', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='support_sup_status_52a4ed_idx'), models.Index(fields=['user', '-created_at'], name='support_sup_user_id_7a4186_idx'), models.Index(fields=['priority', '-created_at'], name='support_sup_priorit_f818fe_idx')],
            },
        ),
    ]
