# Generated by Django 4.2.16 on 2026-02-05 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('twitter', 'Twitter'), ('facebook', 'Facebook')], max_length=20)),
                ('platform_user_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('profile_picture_url', models.URLField(blank=True)),
                ('encrypted_access_token', models.TextField()),
                ('encrypted_refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('error', 'Error')], default='active', max_length=20)),
                ('scopes', models.JSONField(default=list)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_error_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('event_type', models.CharField(choices=[('follower_update', 'Follower Update'), ('profile_update', 'Profile Update'), ('post_update', 'Post Update'), ('account_deauthorized', 'Account Deauthorized')], max_length=30)),
                ('platform_user_id', models.CharField(max_length=100)),
                ('raw_data', models.JSONField()),
                ('processed_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['platform', 'platform_user_id'], name='social_medi_platfor_e52143_idx'), models.Index(fields=['status', 'received_at'], name='social_medi_status_6463ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='FollowerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_count', models.PositiveIntegerField()),
                ('following_count', models.PositiveIntegerField(default=0)),
                ('posts_count', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('sync_source', models.CharField(default='api', max_length=50)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_history', to='social_media.socialmediaaccount')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('job_type', models.CharField(choices=[('full_sync', 'Full Sync'), ('user_sync', 'User Sync'), ('platform_sync', 'Platform Sync'), ('single_account', 'Single Account')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('platform', models.CharField(blank=True, max_length=20)),
                ('accounts_processed', models.IntegerField(default=0)),
                ('accounts_successful', models.IntegerField(default=0)),
                ('accounts_failed', models.IntegerField(default=0)),
                ('error_details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('social_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_media.socialmediaaccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='social_medi_status_3ba340_idx'), models.Index(fields=['job_type'], name='social_medi_job_typ_cbdbf6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='socialmediaaccount',
            index=models.Index(fields=['user', 'platform'], name='social_medi_user_id_a00ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediaaccount',
            index=models.Index(fields=['status'], name='social_medi_status_ff8431_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediaaccount',
            index=models.Index(fields=['last_sync'], name='social_medi_last_sy_f4b7ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='socialmediaaccount',
            unique_together={('user', 'platform')},
        ),
        migrations.AddIndex(
            model_name='followerhistory',
            index=models.Index(fields=['social_account', 'recorded_at'], name='social_medi_social__220756_idx'),
        ),
        migrations.AddIndex(
            model_name='followerhistory',
            index=models.Index(fields=['recorded_at'], name='social_medi_recorde_02b90c_idx'),
        ),
    ]
